# Reproduce the **q** code in Python, as 'functionally' as possible

In [108]:
from operator import add
from functools import partial
from numpy import array, insert

In [124]:
def shift(a):   return insert(a,0,0)[:-1]
def deltas (a): return a - shift(a)  # We CAN do this purely functionally but it's much more verbose

In [125]:
# implement sums and mins in a functional way
def scanl_(f, base, l):
    for x in l:
        base = f(base, x)
        yield base # this would be done with recursion in a purely functional world.
scanl = lambda f,base,l: array(list(scanl_(f,base,l)))
sums  = partial(scanl,add,0)
mins  = lambda x,l:array(list(map(partial(min,x),l)))

### Reproduce the following Q code

```q

q)buys:2 1 3 4 5 2 6f
q)buys
2 1 3 4 5 2 6f
q)count buys
7
q)sell:12
q)sums buys
2 3 6 10 15 17 23f
q)sell
12
q)sell & sums buys
2 3 6 10 12 12 12f
q)deltas sell & sums buys
2 1 3 4 2 0 0f
q)buys
2 1 3 4 5 2 6f
q)buys - (deltas sell & sums buys)
0 0 0 0 3 2 6f

```



In [126]:
buys = array([2,1,3,4,5,2,6])
sell = 12

In [127]:
print(f'''
q)buys
{buys}
q)count buys
{len(buys)}
q)sums buys
{sums(buys)}
q)sell
{sell}
q)sell & sums buys
{mins(sell, (sums(buys)))}
q)deltas sell & sums buys
{deltas(mins(sell, (sums(buys))))}
q)buys - (deltas sell & sums buys)
{buys - deltas(mins(sell,(sums(buys))))}
''')


q)buys
[2 1 3 4 5 2 6]
q)count buys
7
q)sums buys
[ 2  3  6 10 15 17 23]
q)sell
12
q)sell & sums buys
[ 2  3  6 10 12 12 12]
q)deltas sell & sums buys
[2 1 3 4 2 0 0]
q)buys - (deltas sell & sums buys)
[0 0 0 0 3 2 6]

